# Generated by Django 5.0.2 on 2024-02-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='media/thumbnails/')),
                ('video', models.FileField(upload_to='media/videos/')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
    ]
